rem Copying macros...
copy x_macros.sqf 3d /Y
copy x_macros.sqf 3d\functions /Y
copy x_macros.sqf 3d\modules /Y
copy x_macros.sqf admin /Y
copy x_macros.sqf admin\modules /Y
copy x_macros.sqf airdrop /Y
copy x_macros.sqf airdrop\functions /Y
copy x_macros.sqf airdrop\modules /Y
copy x_macros.sqf airtaxi /Y
copy x_macros.sqf airtaxi\functions /Y
copy x_macros.sqf ammobox /Y
copy x_macros.sqf ammobox\modules /Y
copy x_macros.sqf ammobox\functions /Y
copy x_macros.sqf artillery /Y
copy x_macros.sqf artillery\functions /Y
copy x_macros.sqf backpack /Y
copy x_macros.sqf backpack\functions /Y
copy x_macros.sqf base /Y
copy x_macros.sqf base_ammobox /Y
copy x_macros.sqf base_bonus /Y
copy x_macros.sqf base_halo /Y
copy x_macros.sqf base_wreck /Y
copy x_macros.sqf base_wreck\functions /Y
copy x_macros.sqf base_wreck\modules /Y
copy x_macros.sqf board /Y
copy x_macros.sqf chat /Y
copy x_macros.sqf cleanup /Y
copy x_macros.sqf cleanup\functions /Y
copy x_macros.sqf communication /Y
copy x_macros.sqf communication\functions /Y
copy x_macros.sqf communication\modules /Y
copy x_macros.sqf construction /Y
copy x_macros.sqf construction\functions /Y
copy x_macros.sqf core\client /Y
copy x_macros.sqf core\client\functions /Y
copy x_macros.sqf core\common /Y
copy x_macros.sqf core\common\functions /Y
copy x_macros.sqf core\common\scripts /Y
copy x_macros.sqf core\helper /Y
copy x_macros.sqf core\helper\functions /Y
copy x_macros.sqf core\network /Y
copy x_macros.sqf core\server /Y
copy x_macros.sqf core\server\functions /Y
copy x_macros.sqf crossroad /Y
copy x_macros.sqf crossroad\functions /Y
copy x_macros.sqf debug /Y
copy x_macros.sqf debug\functions /Y
copy x_macros.sqf debug\modules /Y
copy x_macros.sqf drag /Y
copy x_macros.sqf drag\functions /Y
copy x_macros.sqf farp /Y
copy x_macros.sqf farp\modules /Y
copy x_macros.sqf fortification /Y
copy x_macros.sqf fortification\modules /Y
copy x_macros.sqf gesture /Y
copy x_macros.sqf gesture\functions /Y
copy x_macros.sqf gesture\modules /Y
copy x_macros.sqf halo /Y
copy x_macros.sqf halo\functions /Y
copy x_macros.sqf halo\functions\bis /Y
copy x_macros.sqf halo\modules /Y
copy x_macros.sqf heap /Y
copy x_macros.sqf heap\functions /Y
copy x_macros.sqf idle /Y
copy x_macros.sqf ied /Y
copy x_macros.sqf ied\functions /Y
copy x_macros.sqf intel /Y
copy x_macros.sqf intel\functions /Y
copy x_macros.sqf intel\modules /Y
copy x_macros.sqf inventory /Y
copy x_macros.sqf inventory\functions /Y
copy x_macros.sqf inventory\modules /Y
copy x_macros.sqf loadout /Y
copy x_macros.sqf loadout\functions /Y
copy x_macros.sqf marker /Y
copy x_macros.sqf marker\functions /Y
copy x_macros.sqf mash /Y
copy x_macros.sqf mash\modules /Y
copy x_macros.sqf medical /Y
copy x_macros.sqf medical\functions /Y
copy x_macros.sqf medical\modules /Y
copy x_macros.sqf mission_main /Y
copy x_macros.sqf mission_main\functions /Y
copy x_macros.sqf mission_main\modules /Y
copy x_macros.sqf mission_side /Y
copy x_macros.sqf mission_side\functions /Y
copy x_macros.sqf mission_side\missions\crash /Y
copy x_macros.sqf name /Y
copy x_macros.sqf name\functions /Y
copy x_macros.sqf nest /Y
copy x_macros.sqf nest\modules /Y
copy x_macros.sqf option /Y
copy x_macros.sqf option\modules /Y
copy x_macros.sqf perimiter /Y
copy x_macros.sqf perimiter\functions /Y
copy x_macros.sqf perk /Y
copy x_macros.sqf perk\functions /Y
copy x_macros.sqf perk\modules /Y
copy x_macros.sqf respawn /Y
copy x_macros.sqf respawn\functions /Y
copy x_macros.sqf respawn\modules /Y
copy x_macros.sqf revive /Y
copy x_macros.sqf revive\functions /Y
copy x_macros.sqf revive\modules /Y
copy x_macros.sqf setting /Y
copy x_macros.sqf setting\functions /Y
copy x_macros.sqf shield /Y
copy x_macros.sqf shield\functions /Y
copy x_macros.sqf spectate /Y
copy x_macros.sqf spectate\modules /Y
copy x_macros.sqf squad /Y
copy x_macros.sqf squad\functions /Y
copy x_macros.sqf task /Y
copy x_macros.sqf task\functions /Y
copy x_macros.sqf teleport /Y
copy x_macros.sqf teleport\modules /Y
copy x_macros.sqf teleport\functions /Y
copy x_macros.sqf uav /Y
copy x_macros.sqf uav\functions /Y
copy x_macros.sqf uav\modules /Y
copy x_macros.sqf unit /Y
copy x_macros.sqf unit\functions /Y
copy x_macros.sqf unit\modules /Y
copy x_macros.sqf vehicle /Y
copy x_macros.sqf vehicle\functions /Y
copy x_macros.sqf vehicle\functions\offsets /Y
copy x_macros.sqf vehicle\modules /Y
copy x_macros.sqf vehicle_ammobox /Y
copy x_macros.sqf vehicle_ammobox\functions /Y
copy x_macros.sqf vehicle_ammobox\modules /Y
copy x_macros.sqf vehicle_bonus /Y
copy x_macros.sqf vehicle_bonus\modules /Y
copy x_macros.sqf vehicle_create /Y
copy x_macros.sqf vehicle_create\functions /Y
copy x_macros.sqf vehicle_create\modules /Y
copy x_macros.sqf vehicle_deploy /Y
copy x_macros.sqf vehicle_deploy\functions /Y
copy x_macros.sqf vehicle_deploy\modules /Y
copy x_macros.sqf vehicle_flip /Y
copy x_macros.sqf vehicle_flip\functions /Y
copy x_macros.sqf vehicle_flip\modules /Y
copy x_macros.sqf vehicle_fob /Y
copy x_macros.sqf vehicle_fob\modules /Y
copy x_macros.sqf vehicle_lift /Y
copy x_macros.sqf vehicle_lift\functions /Y
copy x_macros.sqf vehicle_lift\modules /Y
copy x_macros.sqf vehicle_load /Y
copy x_macros.sqf vehicle_load\functions /Y
copy x_macros.sqf vehicle_load\modules /Y
copy x_macros.sqf vehicle_marker /Y
copy x_macros.sqf vehicle_marker\functions /Y
copy x_macros.sqf vehicle_marker\modules /Y
copy x_macros.sqf vehicle_pack /Y
copy x_macros.sqf vehicle_pack\functions /Y
copy x_macros.sqf vehicle_pack\modules /Y
copy x_macros.sqf vehicle_menu /Y
copy x_macros.sqf vehicle_menu\functions /Y
copy x_macros.sqf vehicle_menu\modules /Y
copy x_macros.sqf vehicle_mhq /Y
copy x_macros.sqf vehicle_mhq\modules /Y
copy x_macros.sqf vehicle_protection /Y
copy x_macros.sqf vehicle_protection\modules /Y
copy x_macros.sqf vehicle_repair /Y
copy x_macros.sqf vehicle_repair\functions /Y
copy x_macros.sqf vehicle_repair\modules /Y
copy x_macros.sqf vehicle_respawn /Y
copy x_macros.sqf vehicle_respawn\functions /Y
copy x_macros.sqf vehicle_respawn\modules /Y
copy x_macros.sqf vehicle_service /Y
copy x_macros.sqf vehicle_service\functions /Y
copy x_macros.sqf vehicle_service\modules /Y
copy x_macros.sqf vehicle_teleport /Y
copy x_macros.sqf vehicle_teleport\functions /Y
copy x_macros.sqf vehicle_teleport\modules /Y
copy x_macros.sqf vehicle_tow /Y
copy x_macros.sqf vehicle_tow\functions /Y
copy x_macros.sqf vehicle_tow\modules /Y
copy x_macros.sqf vehicle_welcome /Y
copy x_macros.sqf vehicle_welcome\modules /Y
copy x_macros.sqf vehicle_wreck /Y
copy x_macros.sqf vehicle_wreck\functions /Y
copy x_macros.sqf vehicle_wreck\modules /Y
copy x_macros.sqf weather /Y